# Generated by Django 5.2.14 on 2026-07-01 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_card_carditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carditem',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.card'),
        ),
    ]
